/*

 BATTLE_STATS_BOX_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : C:\Users\newgb\Documents\Game Boy\gbtd22\battle.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Battle_Stats_Box_MapWidth 20
#define Battle_Stats_Box_MapHeight 4
#define Battle_Stats_Box_MapBank 0

extern unsigned char Battle_Stats_Box_Map[];

/* End of BATTLE_STATS_BOX_MAP.H */
