/*

 BATTLE_ARROW_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\Users\Virtu\GBTD_GBMB Gameboy Development Tools\GBTD\Arrow Left.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Battle_Arrow_Map_h_INCLUDE
#define __Battle_Arrow_Map_h_INCLUDE

#define Battle_Arrow_MapWidth 3
#define Battle_Arrow_MapHeight 3
#define Battle_Arrow_MapBank 0

extern const unsigned char Battle_Arrow_Map[];

#endif

/* End of BATTLE_ARROW_MAP.H */
