/*

 BATTLE_ARROW_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : C:\Users\Virtu\GBTD_GBMB Gameboy Development Tools\GBTD\Arrow Left.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Battle_Arrow_MapWidth 3
#define Battle_Arrow_MapHeight 3
#define Battle_Arrow_MapBank 0

const unsigned char Battle_Arrow_Map[] =
{
  0x05,0x02,0x05,0x00,0x03,0x01,0x05,0x03,0x05
};

/* End of BATTLE_ARROW_MAP.C */
