/*

 LETTERS_EXTRA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 40 to 43

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Letters_ExtraBank 0
/* Start of tile array. */
extern unsigned char Letters_Extra[];

/* End of LETTERS_EXTRA.H */
