/*

 MENU_BG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 4
   Tile set      : C:\Users\newgb\Documents\Game Boy\gbtd22\menu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Menu_BG_MapWidth 10
#define Menu_BG_MapHeight 4
#define Menu_BG_MapBank 0

extern unsigned char Menu_BG_Map[];

/* End of MENU_BG_MAP.H */
