/*

 TEXTBOXMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : C:\Users\newgb\Documents\Game Boy\gbtd22\dia3.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TextBoxMapWidth 20
#define TextBoxMapHeight 6
#define TextBoxMapBank 0

unsigned char TextBoxMap[] =
{
  0x11,0x42,0x22,0x22,0x22,0x22,0x22,0x22,0x24,
  0x11,0x15,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x51,0x13,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x31,0x13
};

/* End of TEXTBOXMAP.C */
