/*

 TEXTBOXMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : C:\Users\newgb\Documents\Game Boy\gbtd22\dia3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TextBoxMapWidth 20
#define TextBoxMapHeight 6
#define TextBoxMapBank 0

extern const unsigned char TextBoxMap[];

/* End of TEXTBOXMAP.H */
