/*

 TOP_TEXTBOX.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 37 to 38

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Top_textbox_h_INCLUDE
#define __Top_textbox_h_INCLUDE

/* Bank of tiles. */
#define Top_textboxBank 0
/* Start of tile array. */
extern const unsigned char Top_textbox[];

#endif

/* End of TOP_TEXTBOX.H */
