/*

 2X2TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 31

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __2x2tiles_h_INCLUDE
#define __2x2tiles_h_INCLUDE

/* Bank of tiles. */
#define TilesBank 0
/* Start of tile array. */
extern const unsigned char Tiles[];

#endif

/* End of 2X2TILES.H */
