/* 
 Generated By GameBoyPngConverter

 Tiles map

 TileMap Size      : 8 x 10
*/ 

#ifndef BANDIT_TEXT_MAP_H
#define BANDIT_TEXT_MAP_H

extern const unsigned char bandit_text_map_left[];
extern const unsigned char bandit_text_map_right[];

#endif