/* 
 Generated By GameBoyPngConverter

 Tiles map

 TileMap Size      : 8 x 10
*/ 

#ifndef BOSTON_TEXT_MAP_H
#define BOSTON_TEXT_MAP_H

extern const unsigned char boston_text_map_left[];
extern const unsigned char boston_text_map_right[];

#endif