/* 
 Generated By GameBoyPngConverter

 Tiles map

 TileMap Size      : 8 x 9
*/ 

#ifndef ELF_TEXT_MAP_H
#define ELF_TEXT_MAP_H

extern const unsigned char elf_text_map_left[];
extern const unsigned char elf_text_map_right[];

#endif