/* 
 Generated By GameBoyPngConverter

 Tiles map

 TileMap Size      : 8 x 9
*/ 

#ifndef FREDERIK_TEXT_MAP_H
#define FREDERIK_TEXT_MAP_H

extern const unsigned char frederik_text_map_left[];
extern const unsigned char frederik_text_map_right[];

#endif