/* 
 Generated By GameBoyPngConverter

 Tiles map

 TileMap Size      : 8 x 9
*/ 

#ifndef MARIE_TEXT_MAP_LEFT_H
#define MARIE_TEXT_MAP_LEFT_H

extern const unsigned char marie_text_map_left[];
extern const unsigned char marie_text_map_right[];

#endif